### PR TITLE
Add aliases/ snippets for python, python-virtualenv and anaconda

### PR DESCRIPTION
**Pull request by diningPhilosopher64**
**[Explain what this alias/snippet is about and why it should be included here.]**
The aliases and snippets are to simplify the working with python both for the default `virtualenv` and anaconda environments.

Fixes #{46}

## By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read the [Contribution guidelines](https://github.com/aashutoshrathi/awesome-bashrc/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable.
- [x] This pull request has a descriptive title. For example, `Add [Alias name]`, not `Update readme.md` or `Added new entries`.
- [x] The snippet/alias I added is not a duplicate.

-----
[View rendered README.md](https://github.com/diningPhilosopher64/awesome-bashrc/blob/python-aliases/README.md)

### CODE REVIEW

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Hey! Can you also update Content's Table on top of README, with this nested list

**Comment by diningPhilosopher64** [comment]
Updated as per review comments!

**Review by aashutoshrathi — APPROVED** [review]

**Comment by aashutoshrathi** [comment]
Hey! @diningPhilosopher64 
Just wanted to confirm this PR has nothing to do with Naag Panchami, right? 😂

**Comment by diningPhilosopher64** [comment]
@aashutoshrathi  🤣🤣🤣. Good one.

I just happened to discover your repo when searching for bashrc files!

**Pull request merged**
